TELEGRAM_KEY = "6812403178:AAGxEXPGHNFUrK2gwok7m5f6b6f9ruv3Eok"
HUGGING_FACE_KEY = "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"
OPENAI_KEY = "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"
ZOTERO_KEY = None
ZOTERO_ID = None